package lk.ijse.gdse71.serenitymentalhealththerapycentersystem.controller;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import lk.ijse.gdse71.serenitymentalhealththerapycentersystem.dto.tm.TherapySessionTM;

import java.time.LocalDate;

public class SessionController {

    @FXML
    private Button btnDelete;

    @FXML
    private Button btnReset;

    @FXML
    private Button btnSave;

    @FXML
    private Button btnUpdate;

    @FXML
    private Button btnView;

    @FXML
    private ComboBox cmbPatients;

    @FXML
    private ComboBox cmbPrograms;

    @FXML
    private ComboBox cmbStatus;

    @FXML
    private ComboBox cmbTherapist;

    @FXML
    private TableColumn<TherapySessionTM, LocalDate> colDate;

    @FXML
    private TableColumn<TherapySessionTM, String> colPatientId;

    @FXML
    private TableColumn<TherapySessionTM, String> colPatinet;

    @FXML
    private TableColumn<TherapySessionTM, String> colProgram;

    @FXML
    private TableColumn<TherapySessionTM, String> colProgramId;

    @FXML
    private TableColumn<TherapySessionTM, LocalDate> colSessionDate;

    @FXML
    private TableColumn<TherapySessionTM, String> colSessionId;

    @FXML
    private TableColumn<TherapySessionTM, String> colTherapist;

    @FXML
    private TableColumn<TherapySessionTM, String> colTherapistId;

    @FXML
    private DatePicker datePickerForSession;

    @FXML
    private Label lblAutoGeneratedId;

    @FXML
    private Label lblDate;

    @FXML
    private Label lblDesc;

    @FXML
    private Label lblPatient;

    @FXML
    private Label lblPaymentId;

    @FXML
    private Label lblProgram;

    @FXML
    private Label lblSessionDate;

    @FXML
    private Label lblTherapist;

    @FXML
    private VBox paymentVBox;

    @FXML
    private AnchorPane sessionAnchorPane;

    @FXML
    private TableView<TherapySessionTM> sessionTable;

    @FXML
    private TextField txtAmount;

    @FXML
    private TextField txtDesc;

    @FXML
    void deleteBtnOnAction(ActionEvent event) {

    }

    @FXML
    void resetBtnOnAction(ActionEvent event) {

    }

    @FXML
    void saveBtnOnAction(ActionEvent event) {

    }

    @FXML
    void updateBtnOnAction(ActionEvent event) {

    }

}
